//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class @class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public @class()
        {
            this.class_routine = new HashSet<class_routine>();
            this.results = new HashSet<result>();
            this.students = new HashSet<student>();
        }

        [Display(Name = "Class Id : ")]
        public int id { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Class :")]
        public string name { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Section :")]
        public string section { get; set; }

        [Display(Name = "Maths :")]
        public Nullable<bool> IsMaths { get; set; }

        [Display(Name = "English Literature :")]
        public Nullable<bool> IsEnglishLiterature { get; set; }

        [Display(Name = "English Grammar :")]
        public Nullable<bool> IsEnglishGrammar { get; set; }

        [Display(Name = "Urdu :")]
        public Nullable<bool> IsUrdu { get; set; }

        [Display(Name = "Islamiyat :")]
        public Nullable<bool> IsIslamiyat { get; set; }

        [Display(Name = "Science :")]
        public Nullable<bool> IsScience { get; set; }

        [Display(Name = "Physics :")]
        public Nullable<bool> IsPhysics { get; set; }

        [Display(Name = "Chemistry :")]
        public Nullable<bool> IsChemistry { get; set; }

        [Display(Name = "Computer :")]
        public Nullable<bool> IsComputer { get; set; }

        [Display(Name = "History :")]
        public Nullable<bool> IsHistory { get; set; }

        [Display(Name = "Geography :")]
        public Nullable<bool> IsGeography { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<class_routine> class_routine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result> results { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student> students { get; set; }
    }

    public partial class JoinClasses
    {
        [Display(Name = "Class Id : ")]
        public int id { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Class :")]
        public string name { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Section :")]
        public string section { get; set; }

        [Display(Name = "Maths :")]
        public Nullable<bool> IsMaths { get; set; }

        [Display(Name = "English Literature :")]
        public Nullable<bool> IsEnglishLiterature { get; set; }

        [Display(Name = "English Grammar :")]
        public Nullable<bool> IsEnglishGrammar { get; set; }

        [Display(Name = "Urdu :")]
        public Nullable<bool> IsUrdu { get; set; }

        [Display(Name = "Islamiyat :")]
        public Nullable<bool> IsIslamiyat { get; set; }

        [Display(Name = "Science :")]
        public Nullable<bool> IsScience { get; set; }

        [Display(Name = "Physics :")]
        public Nullable<bool> IsPhysics { get; set; }

        [Display(Name = "Chemistry :")]
        public Nullable<bool> IsChemistry { get; set; }

        [Display(Name = "Computer :")]
        public Nullable<bool> IsComputer { get; set; }

        [Display(Name = "History :")]
        public Nullable<bool> IsHistory { get; set; }

        [Display(Name = "Geography :")]
        public Nullable<bool> IsGeography { get; set; }
    }
}
