//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class class_routine
    {
        [Required(ErrorMessage = "*")]
        [Display(Name = "Routine Id : ")]
        public int rou_id { get; set; }

        [Required(ErrorMessage = "*")]
        [StringLength(50)]
        [Display(Name = "TimeTable Day : ")]
        public string rou_day { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Class Id : ")]
        public Nullable<int> class_id { get; set; }

        [Display(Name = "Maths : ")]
        public Nullable<bool> IsMaths { get; set; }

        [Display(Name = "Maths Slot : ")]
        public string IsMathsSlot { get; set; }

        [Display(Name = "English Literature : ")]
        public Nullable<bool> IsEnglishLiterature { get; set; }

        [Display(Name = "English Literature Slot : ")]
        public string IsEnglishLiteratureSlot { get; set; }

        [Display(Name = "English Grammar : ")]
        public Nullable<bool> IsEnglishGrammar { get; set; }

        [Display(Name = "English Grammar Slot : ")]
        public string IsEnglishGrammarSlot { get; set; }

        [Display(Name = "Urdu : ")]
        public Nullable<bool> IsUrdu { get; set; }

        [Display(Name = "Urdu Slot : ")]
        public string IsUrduSlot { get; set; }

        [Display(Name = "Islamiyat : ")]
        public Nullable<bool> IsIslamiyat { get; set; }

        [Display(Name = "Islamiyat Slot : ")]
        public string IsIslamiyatSlot { get; set; }

        [Display(Name = "Science : ")]
        public Nullable<bool> IsScience { get; set; }

        [Display(Name = "Science Slot : ")]
        public string IsScienceSlot { get; set; }

        [Display(Name = "Physics : ")]
        public Nullable<bool> IsPhysics { get; set; }

        [Display(Name = "Physics Slot : ")]
        public string IsPhysicsSlot { get; set; }

        [Display(Name = "Chemistry : ")]
        public Nullable<bool> IsChemistry { get; set; }

        [Display(Name = "Chemistry Slot : ")]
        public string IsChemistrySlot { get; set; }

        [Display(Name = "Computer : ")]
        public Nullable<bool> IsComputer { get; set; }

        [Display(Name = "Computer Slot : ")]
        public string IsComputerSlot { get; set; }

        [Display(Name = "History : ")]
        public Nullable<bool> IsHistory { get; set; }

        [Display(Name = "History Slot : ")]
        public string IsHistorySlot { get; set; }

        [Display(Name = "Geography : ")]
        public Nullable<bool> IsGeography { get; set; }

        [Display(Name = "Geography Slot : ")]
        public string IsGeographySlot { get; set; }


        public virtual @class @class { get; set; }
    }

    public partial class JoinTimeTable
    {
        [Display(Name = "Routine Id : ")]
        public int rou_id { get; set; }

        [Display(Name = "TimeTable Day : ")]
        public string rou_day { get; set; }

        [Display(Name = "Class Id : ")]
        public Nullable<int> class_id { get; set; }

        [Display(Name = "Maths : ")]
        public Nullable<bool> IsMaths { get; set; }

        [Display(Name = "Maths Slot : ")]
        public string IsMathsSlot { get; set; }

        [Display(Name = "English Literature : ")]
        public Nullable<bool> IsEnglishLiterature { get; set; }

        [Display(Name = "English Literature Slot : ")]
        public string IsEnglishLiteratureSlot { get; set; }

        [Display(Name = "English Grammar : ")]
        public Nullable<bool> IsEnglishGrammar { get; set; }

        [Display(Name = "English Grammar Slot : ")]
        public string IsEnglishGrammarSlot { get; set; }

        [Display(Name = "Urdu : ")]
        public Nullable<bool> IsUrdu { get; set; }

        [Display(Name = "Urdu Slot : ")]
        public string IsUrduSlot { get; set; }

        [Display(Name = "Islamiyat : ")]
        public Nullable<bool> IsIslamiyat { get; set; }

        [Display(Name = "Islamiyat Slot : ")]
        public string IsIslamiyatSlot { get; set; }

        [Display(Name = "Science : ")]
        public Nullable<bool> IsScience { get; set; }

        [Display(Name = "Science Slot : ")]
        public string IsScienceSlot { get; set; }

        [Display(Name = "Physics : ")]
        public Nullable<bool> IsPhysics { get; set; }

        [Display(Name = "Physics Slot : ")]
        public string IsPhysicsSlot { get; set; }

        [Display(Name = "Chemistry : ")]
        public Nullable<bool> IsChemistry { get; set; }

        [Display(Name = "Chemistry Slot : ")]
        public string IsChemistrySlot { get; set; }

        [Display(Name = "Computer : ")]
        public Nullable<bool> IsComputer { get; set; }

        [Display(Name = "Computer Slot : ")]
        public string IsComputerSlot { get; set; }

        [Display(Name = "History : ")]
        public Nullable<bool> IsHistory { get; set; }

        [Display(Name = "History Slot : ")]
        public string IsHistorySlot { get; set; }

        [Display(Name = "Geography : ")]
        public Nullable<bool> IsGeography { get; set; }

        [Display(Name = "Geography Slot : ")]
        public string IsGeographySlot { get; set; }

        public string ClassName { get; set; }
        public string ClassSection { get; set; }
    }
}
