//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Student_Management_System.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class fee
    {
        public int fees_reciept_no { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Student Id : ")]
        public Nullable<int> fees_std_id { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Issue Date : ")]
        public string fees_IssueDate { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Fees Status : ")]
        public string fees_Status { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Paid Date : ")]
        public string fees_PaidDate { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Payment : ")]
        public double fees_Payment { get; set; }

        [Display(Name = "Previous Charges : ")]
        public Nullable<double> fees_PreviousCharges { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Total Amount : ")]
        public double fees_TotalAmount { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Remarks : ")]
        public string fees_Remarks { get; set; }

        public virtual student student { get; set; }
    }

    public partial class Joinfee
    {
        public int fees_reciept_no { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Student Id : ")]
        public Nullable<int> fees_std_id { get; set; }

        [Required(ErrorMessage = "*")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Issue Date : ")]
        public string fees_IssueDate { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Fees Status : ")]
        public string fees_Status { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy/MM/dd}")]
        [Display(Name = "Paid Date : ")]
        public string fees_PaidDate { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Payment : ")]
        public double fees_Payment { get; set; }

        [Display(Name = "Previous Charges : ")]
        public Nullable<double> fees_PreviousCharges { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Total Amount : ")]
        public double fees_TotalAmount { get; set; }

        [Required(ErrorMessage = "*")]
        [Display(Name = "Remarks : ")]
        public string fees_Remarks { get; set; }

        public string ClassName { get; set; }
        public string StudentFname { get; set; }
        public string StudentLname { get; set; }
        public string ClassSection { get; set; }
    }
}
